# Generated by Django 2.1.2 on 2021-12-11 15:53

import Static_Summary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='videoFile',
            field=models.FileField(default='dummy.txt', upload_to='documents/', validators=[Static_Summary.models.validate_geeks_mail]),
        ),
    ]
