# Generated by Django 2.1.2 on 2021-07-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181118_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='summarizationTime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summarizeType',
        ),
    ]
