# Generated by Django 2.1.2 on 2021-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210704_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summarizationTime',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=4),
        ),
        migrations.AddField(
            model_name='document',
            name='summarizeType',
            field=models.CharField(choices=[('LR', 'Lex Rank'), ('LU', 'Luhn'), ('LS', 'LSA'), ('TR', 'Text Rank')], default='LR', max_length=2),
        ),
    ]
