# Generated by Django 2.1.2 on 2021-07-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210705_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='summarizationTime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summarizeType',
        ),
    ]
