# Generated by Django 2.1.2 on 2021-12-13 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210705_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='videoFile',
            field=models.FileField(default='dummy.txt', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
